// Menu transcribed from the printed Little Sheep Hot Pot menu (HPM MAY 26-V8).
// Prices in US dollars. Where a menu line shows two prices (e.g. "10/29") the
// first is `price` and the second `price_large` — small/large or half/full pot.

module.exports = [
  {
    name: 'Chef Speciality', name_zh: '主厨推荐',
    items: [
      { code: 'A1', name: 'Scallion Pancake with Italian Black Truffle Mayo', name_zh: '葱香煎饼佐意大利黑松露蛋黄酱', price: 12 },
      { code: 'A2', name: 'Prime Beef Fried Rice', name_zh: '甄选牛肉炒饭', price: 19 },
      { code: 'A3', name: 'Lamb Fried Rice', name_zh: '羊肉炒饭', price: 16 },
      { code: 'A4', name: 'Vegetable Fried Rice', name_zh: '蔬菜炒饭', price: 16 },
      { code: 'A5', name: 'Pan Fried Dumplings', name_zh: '煎饺', price: 12 },
      { code: 'A6', name: 'Edamame', name_zh: '毛豆', price: 7 },
      { code: 'A7', name: 'Seaweed Salad', name_zh: '海藻沙拉', price: 8 },
      { code: 'K1', name: 'Signature Lamb Kebab', name_zh: '招牌豪气羊肉串', price: 14 },
      { code: 'K2', name: 'Signature Beef Kebab', name_zh: '招牌牛肉串', price: 14 },
      { code: 'K3', name: 'Mongolian Style Roasted Lamb Shank', name_zh: '蒙氏烤小羊腿', price: 26 },
      { code: 'K4', name: 'Mongolian Style Roasted Lamb Chop', name_zh: '主厨烤羊排', price: 21 },
      { code: 'K5', name: 'Popcorn Chicken', name_zh: '黄金酥脆鸡米花', price: 13 },
    ],
  },
  {
    name: 'Soup Base', name_zh: '汤底',
    note: 'Two prices: half pot / full pot. Ask your server about the Seasonal Special.',
    items: [
      { code: 'S1', name: 'Classic Original Soup Base', name_zh: '经典原味锅', price: 10, price_large: 29 },
      { code: 'S2', name: 'Spicy Soup Base', name_zh: '经典香辣锅', price: 10, price_large: 29 },
      { code: 'S3', name: 'Mushroom Soup Base', name_zh: '鲜香菌菇锅', price: 10, price_large: 29 },
      { code: 'S4', name: 'Tomato Soup Base', name_zh: '浓香番茄锅', price: 10, price_large: 29 },
      { code: 'S5', name: 'Signature Chicken Soup Base', name_zh: '特色鸡汤锅', price: 12, price_large: 35 },
      { code: 'S6', name: 'Seasonal Special', name_zh: '季节限定', price: 12, price_large: 35 },
    ],
  },
  {
    name: 'A5 Japanese Wagyu Beef', name_zh: '日本和牛',
    items: [
      { code: 'W1', name: 'Japanese A5 Wagyu Chuck Roll Slice', name_zh: 'A5日本和牛上脑', price: 42 },
      { code: 'W2', name: 'Japanese A5 Wagyu Ribeye', name_zh: 'A5日本和牛肋眼', price: 72 },
      { code: 'W3', name: 'Japanese A5 Wagyu Ribeye Cap', name_zh: 'A5日本和牛肋眼盖', price: 68 },
      { code: 'W4', name: 'Japanese A5 Wagyu Ribeye Cap Cube', name_zh: 'A5日本和牛粒', price: 48 },
    ],
  },
  {
    name: 'Featured Lamb', name_zh: '招牌羊肉',
    items: [
      { code: 'L1', name: 'Lamb Leg Slice', name_zh: '草原羊腿肉', price: 18, price_large: 35 },
      { code: 'L2', name: 'Signature Lamb Shoulder Roll', name_zh: '招牌羊肉卷', price: 19, price_large: 36 },
      { code: 'L3', name: 'Premium Lamb Flap', name_zh: '精选羔羊腩', price: 27, price_large: 37 },
      { code: 'L4', name: 'Cumin Marinated Lamb', name_zh: '火锅孜然羊肉', price: 20 },
    ],
  },
  {
    name: 'Premium Beef', name_zh: '精品牛肉', note: 'All Black Angus.',
    items: [
      { code: 'B1', name: 'Classic Fatty Beef Slice', name_zh: '经典肥牛', price: 19 },
      { code: 'B2', name: 'Black Angus Beef Ribeye Slice', name_zh: '安格斯肋眼', price: 36 },
      { code: 'B3', name: 'Featured Spicy Beef', name_zh: '秘制麻辣牛肉片', price: 19 },
      { code: 'B4', name: 'Black Angus Boneless Short Ribs', name_zh: '安格斯精选无骨牛小排', price: 30 },
      { code: 'B5', name: 'Prime Flat Iron Steak', name_zh: '雪花扁铁牛排', price: 25 },
      { code: 'B6', name: 'Beef Tripe - Black', name_zh: '黑毛肚', price: 12 },
      { code: 'B7', name: 'Beef Tripe - White', name_zh: '牛百叶', price: 12 },
      { code: 'B8', name: 'Beef Tongue', name_zh: '牛舌', price: 16 },
    ],
  },
  {
    name: 'Pork & Chicken', name_zh: '猪肉鸡肉',
    items: [
      { code: 'P1', name: 'Marinated Chicken', name_zh: '调味鸡肉', price: 18 },
      { code: 'P2', name: 'Pork Belly', name_zh: '猪五花肉', price: 16 },
      { code: 'P3', name: 'Premium Pork', name_zh: '雪花猪肉', price: 16 },
      { code: 'P4', name: 'Pork Jowls', name_zh: '猪脸肉', price: 15 },
    ],
  },
  {
    name: 'Seafood', name_zh: '海鲜',
    items: [
      { code: 'H1', name: 'Tiger Shrimp', name_zh: '老虎虾', price: 21 },
      { code: 'H2', name: 'Lobster Tail', name_zh: '龙虾尾', price: 26 },
      { code: 'H3', name: 'Langostino', name_zh: '螯虾', price: 21 },
      { code: 'H4', name: 'Squid', name_zh: '鱿鱼', price: 11 },
      { code: 'H5', name: 'Abalone (6 pcs)', name_zh: '鲍鱼', price: 19 },
      { code: 'H6', name: 'Mussel', name_zh: '青口', price: 11 },
      { code: 'H7', name: 'Black Fish Fillet', name_zh: '黑鱼片', price: 17 },
      { code: 'H8', name: 'Buffalo Carp Fish Fillet', name_zh: '皖鱼片', price: 17 },
      { code: 'H9', name: 'Scallop', name_zh: '鲜元贝', price: 21 },
      { code: 'H10', name: 'Razor Clam', name_zh: '蛏子', price: 12, is_new: 1 },
      { code: 'H11', name: 'Seafood Combo', name_zh: '海鲜拼盘', price: 70 },
    ],
  },
  {
    name: 'Hot Pot Mate', name_zh: '缤纷涮品',
    items: [
      { code: 'M1', name: 'Tofu', name_zh: '嫩豆腐', price: 7 },
      { code: 'M2', name: 'Frozen Tofu', name_zh: '冻豆腐', price: 7 },
      { code: 'M3', name: 'Fried Tofu Skin Roll', name_zh: '响铃卷', price: 8 },
      { code: 'M4', name: 'Fresh Beancurd Skin', name_zh: '腐竹', price: 9 },
      { code: 'M5', name: 'Dough Stick', name_zh: '油条', price: 8 },
      { code: 'M6', name: 'Crab Stick', name_zh: '蟹味棒', price: 10 },
      { code: 'M7', name: 'Fish Tofu', name_zh: '鱼豆腐', price: 9 },
      { code: 'M8', name: 'Egg Crepe Dumplings', name_zh: '蛋饺', price: 9 },
      { code: 'M9', name: 'Lamb Wonton', name_zh: '羊肉馄饨', price: 10 },
      { code: 'M10', name: 'Konjac Noodle', name_zh: '魔芋丝', price: 7 },
      { code: 'M11', name: 'Rice Cake', name_zh: '年糕', price: 6 },
      { code: 'M12', name: 'Wide Vermicelli Noodles', name_zh: '火锅宽粉', price: 8 },
      { code: 'M13', name: 'Vermicelli Noodles', name_zh: '火锅粉丝', price: 6 },
      { code: 'M14', name: 'Udon Noodle', name_zh: '乌冬面', price: 6 },
      { code: 'M15', name: 'Ramen Noodle', name_zh: '拉面', price: 6 },
      { code: 'M16', name: 'Pho Noodle', name_zh: '越南粉', price: 6 },
      { code: 'M17', name: 'White Rice', name_zh: '白米饭', price: 4 },
      { code: 'M18', name: 'Quail Eggs', name_zh: '鹌鹑蛋', price: 7 },
      { code: 'M19', name: 'Chinese Spam', name_zh: '午餐肉', price: 8, is_new: 1 },
      { code: 'M20', name: 'Chinese Mini Sausage', name_zh: '迷你腊肠', price: 9, is_new: 1 },
      { code: 'M21', name: 'Pig Aorta', name_zh: '黄喉', price: 9, is_new: 1 },
    ],
  },
  {
    name: 'Hot Pot Balls', name_zh: '丸子',
    items: [
      { code: 'C1', name: 'Handmade Shrimp Paste', name_zh: '手工虾滑', price: 13 },
      { code: 'C2', name: 'Fish Ball with Roe', name_zh: '蟹黄鱼籽蛋', price: 9 },
      { code: 'C3', name: 'Fish Ball', name_zh: '鲜嫩鱼丸', price: 8 },
      { code: 'C4', name: 'Fish Ball with Pork Filling', name_zh: '福州鱼丸', price: 9 },
      { code: 'C5', name: 'Juicy Beef Ball with Pork Filling', name_zh: '灌汤牛肉丸', price: 8 },
      { code: 'C6', name: 'Fish Ball with Salted Egg Yolk', name_zh: '咸蛋黄鱼蛋', price: 10 },
      { code: 'C7', name: 'Assorted Balls', name_zh: '丸子拼盘', price: 16 },
      { code: 'C8', name: 'Lobster Balls', name_zh: '龙虾丸', price: 9 },
      { code: 'C9', name: 'Fish Balls with Cheese', name_zh: '芝士鱼丸', price: 9 },
    ],
  },
  {
    name: 'Mushrooms', name_zh: '菌菇',
    items: [
      { code: 'E1', name: 'Shiitake Mushroom', name_zh: '香菇', price: 9 },
      { code: 'E2', name: 'Seafood Mushroom', name_zh: '海鲜菇', price: 9 },
      { code: 'E3', name: 'King Oyster Mushroom', name_zh: '杏鲍菇', price: 9 },
      { code: 'E4', name: 'Enoki Mushroom', name_zh: '金针菇', price: 9 },
      { code: 'E5', name: 'Oyster Mushroom', name_zh: '螺菇', price: 9 },
      { code: 'E6', name: 'Black Fungus', name_zh: '木耳', price: 9 },
      { code: 'E7', name: 'Morel Mushroom', name_zh: '羊肚菌', price: 17 },
      { code: 'E8', name: 'Mushroom Platter', name_zh: '菌菇拼盘', price: 19 },
    ],
  },
  {
    name: 'Vegetables', name_zh: '蔬菜',
    items: [
      { code: 'V1', name: 'Seaweed Knot', name_zh: '海带结', price: 7 },
      { code: 'V2', name: 'Sliced Potato', name_zh: '切片土豆', price: 7 },
      { code: 'V3', name: 'Corn', name_zh: '玉米', price: 7 },
      { code: 'V4', name: 'Lotus Root', name_zh: '莲藕', price: 7 },
      { code: 'V5', name: 'Wintermelon', name_zh: '冬瓜', price: 7 },
      { code: 'V6', name: 'Chinese Yam', name_zh: '山药', price: 8 },
      { code: 'V7', name: 'Pumpkin', name_zh: '南瓜', price: 7 },
      { code: 'V8', name: 'Bamboo Slices', name_zh: '笋尖片', price: 8 },
      { code: 'V9', name: 'Watercress', name_zh: '西洋菜', price: 8 },
      { code: 'V10', name: 'Broccoli', name_zh: '西兰花', price: 7 },
      { code: 'V11', name: 'Bok Choy', name_zh: '青江菜', price: 7 },
      { code: 'V12', name: 'Spinach', name_zh: '菠菜', price: 8 },
      { code: 'V13', name: 'Tong Ho', name_zh: '茼蒿', price: 8 },
      { code: 'V14', name: 'Pea Tips', name_zh: '豆苗', price: 10 },
      { code: 'V15', name: 'Baby Cabbage', name_zh: '娃娃菜', price: 7 },
      { code: 'V16', name: 'Daikon Radish', name_zh: '白萝卜', price: 7 },
      { code: 'V17', name: 'Lettuce', name_zh: '生菜', price: 7 },
      { code: 'V18', name: 'Mountain Jelly Vegetable', name_zh: '贡菜', price: 9 },
      { code: 'V19', name: 'Vegetable Platter', name_zh: '时蔬拼盘', price: 18 },
    ],
  },
  {
    name: 'Beverages', name_zh: '饮料',
    items: [
      { code: 'D1', name: 'Coke', name_zh: '可乐', price: 4 },
      { code: 'D2', name: 'Diet Coke', name_zh: '健怡可乐', price: 4 },
      { code: 'D3', name: 'Coke Zero', name_zh: '可口可乐零度', price: 4 },
      { code: 'D4', name: 'Dr Pepper', name_zh: '博士椒', price: 4 },
      { code: 'D5', name: 'Club Soda', name_zh: '苏打水', price: 4 },
      { code: 'D6', name: 'Sprite', name_zh: '雪碧', price: 4 },
      { code: 'D7', name: 'Ginger Ale', name_zh: '姜汁汽水', price: 4 },
      { code: 'D8', name: 'Orange Fanta', name_zh: '橙味芬达', price: 4 },
      { code: 'D9', name: 'Lemonade', name_zh: '柠檬水', price: 4 },
      { code: 'D10', name: 'Herbal Tea', name_zh: '王老吉', price: 4 },
      { code: 'D11', name: 'Coconut Milk', name_zh: '椰奶', price: 4 },
      { code: 'D12', name: 'Sour Plum Juice', name_zh: '酸梅汤', price: 5 },
      { code: 'D13', name: 'Apple Juice', name_zh: '苹果汁', price: 4 },
      { code: 'D14', name: 'Orange Juice', name_zh: '橙汁', price: 4 },
      { code: 'D15', name: 'Cranberry Juice', name_zh: '蔓越莓汁', price: 4 },
    ],
  },
  {
    name: 'Bubble Tea', name_zh: '珍珠奶茶',
    items: [
      { code: '', name: 'Classic Milk Tea', name_zh: '经典奶茶', price: 7 },
      { code: '', name: 'Thai Milk Tea', name_zh: '泰式奶茶', price: 7 },
      { code: '', name: 'Taro Milk Tea', name_zh: '芋头奶茶', price: 7 },
      { code: '', name: 'Brown Sugar Milk Tea', name_zh: '黑糖奶茶', price: 7 },
      { code: '', name: 'Matcha Milk Tea', name_zh: '抹茶奶茶', price: 7 },
    ],
  },
  {
    name: 'Real Fruit Tea', name_zh: '鲜果茶',
    items: [
      { code: '', name: 'Mango', name_zh: '芒果', price: 7 },
      { code: '', name: 'Strawberry', name_zh: '草莓', price: 7 },
      { code: '', name: 'Lychee', name_zh: '荔枝', price: 7 },
      { code: '', name: 'Passion Fruit', name_zh: '百香果', price: 7 },
      { code: '', name: 'Peach', name_zh: '水蜜桃', price: 7 },
      { code: '', name: 'Grapefruit', name_zh: '西柚', price: 7 },
    ],
  },
  {
    name: 'Toppings', name_zh: '配料',
    items: [
      { code: '', name: 'Crystal Bubble', name_zh: '水晶珍珠', price: 1 },
      { code: '', name: 'Coffee Jelly', name_zh: '咖啡冻', price: 1 },
      { code: '', name: 'Lychee Jelly', name_zh: '荔枝冻', price: 1 },
      { code: '', name: 'Popping Bubble — Strawberry', name_zh: '爆珠 草莓', price: 1 },
      { code: '', name: 'Popping Bubble — Mango', name_zh: '爆珠 芒果', price: 1 },
    ],
  },
  {
    name: 'Dessert', name_zh: '甜品',
    items: [
      { code: '', name: 'Ice Cream (Ube, Thai Tea, Lychee Rose, Seasonal)', name_zh: '冰淇淋', price: 6 },
    ],
  },
];
